[package]
name = "dcvpn_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tun = "0.3"
openssl = "0.10"
clap = "3.0"
toml = "0.5"
